### ISSUE TITLE
Unable to run Aurous.jar on OS X

### ISSUE THREAD

**Issue by drpiou** [AurousGroup/Bug-Tracker#109]
Hi, when trying to execute the latest version on OS X, I get this on terminal :
```
MBP-de-Alex:aurous alex$ java -jar Aurous.jar
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	... 1 more
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/Applications/aurous/mac/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/Applications/aurous/mac/jxbrowser.app/Contents/MacOS"): error=13, Permission denied
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/Applications/aurous/mac/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/Applications/aurous/mac/jxbrowser.app/Contents/MacOS"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more
Exception running application me.aurous.Aurous
Exception in thread "Thread-6" java.lang.NullPointerException
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.b(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Codeusa** [comment]
You need to run chmod R 777 on the directory

**Comment by drpiou** [comment]
Okay, thanks. Now I have this : 
```
MBP-de-Alex:~ alex$ java -jar /Applications/aurous/Aurous.jar 
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.getDefault(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<clinit>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at me.aurous.Aurous.start(Aurous.java:114)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: com.teamdev.jxbrowser.chromium.internal.ChromiumExtractorException: Failed to extract chromium binaries into /Users/alex/mac
	at com.teamdev.jxbrowser.chromium.internal.ChromiumExtractor.extract(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.create(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC$a.<clinit>(Unknown Source)
	... 11 more
Caused by: java.lang.IllegalArgumentException: The /chromium-mac.zip resource cannot be found in JAR files.
	at com.teamdev.jxbrowser.chromium.internal.ZIPExtractor.extract(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.e.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	... 15 more
Exception running application me.aurous.Aurous
```

**Comment by Codeusa** [comment]
run the same command on the mac directory and it should work

**Comment by drpiou** [comment]
Okay it works this way ! Thanks :)
