### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by santozz** [AurousGroup/Bug-Tracker#110]
Hi!
I have an error that says:
Exception in thread "main" java.lang.UnsupportedClassVersionError: me/aurous/Aurous : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

From what I read it says that it's about the java version, I'm in OSX and i have version 1.7 of java. It is possible for you to make a Java's 1.7 version available or I really have to update to 1.8 ?

**Comment by Codeusa** [comment]
1.7 does not support Lambdas and Streams, 1.8 does please download the latest jdk

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by santozz** [comment]
I was afraid it was needed... My problem is that I have to have Android SDK
installed and it explicitly needs version 1.7, is it possible for me to
have two different versions of java on the same machine?

Sorry about that,

Thanks for the really fast answer

*Alexandre Miguel Portela dos Santos*

*e-mail:*      alexandre.santozz@gmail.com
*tel:   *           (+351) 913429823
*skype: *       santosalexandre21
*website: *    http://alexandrempsantos.com


2015-10-12 11:17 GMT+01:00 Andrew Sampson <notifications@github.com>:

**Comment by Codeusa** [comment]
This is the best link i can find to help

https://dzone.com/articles/multiple-versions-java-os-x

**Comment by santozz** [comment]
Got it working, thanks!
