### ISSUE TITLE
Stuck at UTF-8

### ISSUE THREAD

**Issue by samuelleb11** [AurousGroup/Bug-Tracker#129]
I got stuck UTF-8 line after launching... Here is my console output:
s**********n@Win98:~/aurous$ java -jar Aurous.jar
Update finished
Check finished
Launching aurous...
UTF-8

**Comment by Codeusa** [comment]
Run as sudo

**Comment by robertmathew** [comment]
sudo java -jar Aurous.jar
Update finished
Check finished
Launching aurous...
UTF-8
Exception in Application start method
Oct 13, 2015 11:34:12 AM me.aurous.launchwrapper.Updater main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at me.aurous.launchwrapper.AurousLoader.launchAurous(AurousLoader.java:39)
	at me.aurous.launchwrapper.Updater.main(Updater.java:32)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	... 1 more
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/robo/aurous-linux64/linux/jxbrowser-chromium" (in directory "/home/robo/aurous-linux64/linux"): error=13, Permission denied
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/home/robo/aurous-linux64/linux/jxbrowser-chromium" (in directory "/home/robo/aurous-linux64/linux"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more

Exception in thread "Thread-4" java.lang.NullPointerException
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.b(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Codeusa** [comment]
https://github.com/AurousGroup/Bug-Tracker/issues/63

**Comment by robertmathew** [comment]
Fixed. Issue was libgcrypt11. Thanks
