### ISSUE TITLE
[Linux / Slackware 14.1] Can't install, get error.

### ISSUE THREAD

**Issue by TeddStriker** [AurousGroup/Bug-Tracker#51]
Here is the error I am getting. This is right after I execute ```java -jar Aurous.jar```. I am installing from ```~/Downloads/source/``` if that makes a difference.

```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit code: 127
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	... 1 more
Exception running application me.aurous.Aurous
Exception in thread "Thread-4" java.lang.NullPointerException
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.b(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

Latest java sdk is installed. On Slackware 14.1, ```linux kerel i686 Linux 3.10.17-smp``` Don't know what other information you would need. 

Thanks.

**Comment by dmxt** [comment]
Did you execute with `sudo`?

**Comment by TeddStriker** [comment]
Same thing with regular, sudo, and su.

**Comment by iMhack** [comment]
I read somewhere that you need java 8 32 bits. Do you have it ?

**Comment by TeddStriker** [comment]
I have jdk 8u60 i586, which is correct for my platform.

**Comment by iMhack** [comment]
I got same error as you with java 8 64 bits...

**Comment by Codeusa** [comment]
The x32 linux version will not work on the x64 version of Linux, wait for the binaries for x64 to be released

**Comment by TeddStriker** [comment]
```uname -m``` Shows that I'm on i686, and ```file /sbin/init``` says I'm on 32bit. Any other solutions, seeing as waiting for 64bit won't really help me I think.

**Comment by iMhack** [comment]
64bits version is available.
