### ISSUE TITLE
 Nothing happens - Linux x64 

### ISSUE THREAD

**Issue by typical-user** [AurousGroup/Bug-Tracker#80]
I use Xubuntu 14.04 on a  x64.
I did all the steps suggested by the readme file, but when i try to run Aurous from the .jar (obviously with Oracle Java  8 Runtime)   nothing happens. Same story if I try to run it from the console:

alex@AleXubuntu:~/Scrivania/Aurous$ java -jar Aurous.jar
Prism-ES2 Error : GL_VERSION (major.minor) = 1.4
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	... 1 more
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/alex/Scrivania/Aurous/linux/jxbrowser-chromium" (in directory "/home/alex/Scrivania/Aurous/linux"): error=13, Permesso negato
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/home/alex/Scrivania/Aurous/linux/jxbrowser-chromium" (in directory "/home/alex/Scrivania/Aurous/linux"): error=13, Permesso negato
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=13, Permesso negato
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more
Exception running application me.aurous.Aurous
Exception in thread "Thread-4" java.lang.NullPointerException
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.b(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adamundercover** [comment]
try

    chmod +x linux/jxbrowser-chromium

**Comment by Codeusa** [comment]
See #63 for various work arounds.
