### ISSUE TITLE
Won't run on xubuntu 15.04 x64

### ISSUE THREAD

**Issue by davegri** [AurousGroup/Bug-Tracker#85]
I've installed openjfx
jxbrowser-chromium is executable
I'm running as sudo

error:

    ~/Desktop ❯❯❯sudo java -jar Aurous.jar                                                           ⏎
    Exception in Application start method
    java.lang.reflect.InvocationTargetException
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	    at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
    Caused by: java.lang.RuntimeException: Exception in Application start method
	    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	    at     com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	    at com.sun.javafx.application.LauncherImpl$$Lambda$55/1761061602.run(Unknown Source)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit     code: 127
	    at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	    ... 1 more
    Exception running application me.aurous.Aurous
    Exception in thread "Thread-4" java.lang.NullPointerException
	    at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	    at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.b(Unknown Source)
	    at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.a(Unknown Source)
	    at com.teamdev.jxbrowser.chromium.internal.ipc.b.run(Unknown Source)
	    at java.lang.Thread.run(Thread.java:745)

**Comment by davegri** [comment]
Fix is here
http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html
program is laggy as hell though
