### ISSUE TITLE
[Linux][64] QuantumRenderer java error

### ISSUE THREAD

**Issue by JulienMEME** [AurousGroup/Bug-Tracker#99]
Hi,

After downloaded the last version 0.1 64 bits today and used Oracle java 1.8.0_60 (but is not my main JVM, by default java is openjdk version 1.8.0_60), when I launch the command /usr/java/jre1.8.0_60/bin/java -jar Aurous.jar on my openSUSE 13.2, I have this following error:

Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(Unknown Source)
        at com.sun.javafx.tk.Toolkit.getToolkit(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        ... 5 more

One way?
Thanks in advance.

**Comment by Codeusa** [comment]
All linux post at this time are directed to #63

**Comment by JulienMEME** [comment]
Thanks, but runs with the JDK and does not with the JRE.
